// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// protoc-gen-go-http v2.2.0

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

type InstanceHTTPServer interface {
	CreateInstances(context.Context, *CreateInstancesRequest) (*CreateInstancesResponse, error)
	CreateSubnet(context.Context, *CreateSubnetRequest) (*CreateSubnetResponse, error)
	CreateVpc(context.Context, *CreateVpcRequest) (*CreateVpcResponse, error)
	DeleteInstances(context.Context, *DeleteInstancesRequest) (*DeleteInstancesResponse, error)
	DeleteSubnet(context.Context, *DeleteSubnetRequest) (*DeleteSubnetResponse, error)
	DeleteVpc(context.Context, *DeleteVpcRequest) (*DeleteVpcResponse, error)
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	ListInstanceTypes(context.Context, *ListInstanceTypesRequest) (*ListInstanceTypesResponse, error)
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	ListRegions(context.Context, *ListRegionsRequest) (*ListRegionsResponse, error)
	ListSubnets(context.Context, *ListSubnetsRequest) (*ListSubnetsResponse, error)
	ListVpcs(context.Context, *ListVpcsRequest) (*ListVpcsResponse, error)
	RebootInstances(context.Context, *RebootInstancesRequest) (*RebootInstancesResponse, error)
	ShowJob(context.Context, *ShowJobRequest) (*ShowJobResponse, error)
	ShowSubnet(context.Context, *ShowSubnetRequest) (*ShowSubnetResponse, error)
	ShowVpc(context.Context, *ShowVpcRequest) (*ShowVpcResponse, error)
	StartInstances(context.Context, *StartInstancesRequest) (*StartInstancesResponse, error)
	StopInstances(context.Context, *StopInstancesRequest) (*StopInstancesResponse, error)
	UpdateSubnet(context.Context, *UpdateSubnetRequest) (*UpdateSubnetResponse, error)
	UpdateVpc(context.Context, *UpdateVpcRequest) (*UpdateVpcResponse, error)
}

func RegisterInstanceHTTPServer(s *http.Server, srv InstanceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/regions", _Instance_ListRegions0_HTTP_Handler(srv))
	r.GET("/api/images", _Instance_ListImages0_HTTP_Handler(srv))
	r.GET("/api/instance-types", _Instance_ListInstanceTypes0_HTTP_Handler(srv))
	r.POST("/api/instances", _Instance_CreateInstances0_HTTP_Handler(srv))
	r.GET("/api/instances", _Instance_ListInstances0_HTTP_Handler(srv))
	r.GET("/api/job", _Instance_ShowJob0_HTTP_Handler(srv))
	r.PUT("/api/instances/start", _Instance_StartInstances0_HTTP_Handler(srv))
	r.PUT("/api/instances/stop", _Instance_StopInstances0_HTTP_Handler(srv))
	r.PUT("/api/instances/reboot", _Instance_RebootInstances0_HTTP_Handler(srv))
	r.PUT("/api/instances/terminate", _Instance_DeleteInstances0_HTTP_Handler(srv))
	r.POST("/api/vpc", _Instance_CreateVpc0_HTTP_Handler(srv))
	r.DELETE("/api/vpc", _Instance_DeleteVpc0_HTTP_Handler(srv))
	r.GET("/api/vpc", _Instance_ListVpcs0_HTTP_Handler(srv))
	r.GET("/api/vpc/query", _Instance_ShowVpc0_HTTP_Handler(srv))
	r.PUT("/api/vpc", _Instance_UpdateVpc0_HTTP_Handler(srv))
	r.POST("/api/subnet", _Instance_CreateSubnet0_HTTP_Handler(srv))
	r.DELETE("/api/subnet", _Instance_DeleteSubnet0_HTTP_Handler(srv))
	r.GET("/api/subnet", _Instance_ListSubnets0_HTTP_Handler(srv))
	r.GET("/api/subnet/query", _Instance_ShowSubnet0_HTTP_Handler(srv))
	r.PUT("/api/subnet", _Instance_UpdateSubnet0_HTTP_Handler(srv))
}

func _Instance_ListRegions0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRegionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/ListRegions")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRegions(ctx, req.(*ListRegionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRegionsResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_ListImages0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListImagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/ListImages")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListImages(ctx, req.(*ListImagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListImagesResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_ListInstanceTypes0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListInstanceTypesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/ListInstanceTypes")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListInstanceTypes(ctx, req.(*ListInstanceTypesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListInstanceTypesResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_CreateInstances0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateInstancesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/CreateInstances")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateInstances(ctx, req.(*CreateInstancesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateInstancesResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_ListInstances0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListInstancesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/ListInstances")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListInstances(ctx, req.(*ListInstancesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListInstancesResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_ShowJob0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ShowJobRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/ShowJob")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ShowJob(ctx, req.(*ShowJobRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ShowJobResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_StartInstances0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StartInstancesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/StartInstances")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StartInstances(ctx, req.(*StartInstancesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StartInstancesResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_StopInstances0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in StopInstancesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/StopInstances")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.StopInstances(ctx, req.(*StopInstancesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*StopInstancesResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_RebootInstances0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RebootInstancesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/RebootInstances")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RebootInstances(ctx, req.(*RebootInstancesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RebootInstancesResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_DeleteInstances0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteInstancesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/DeleteInstances")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteInstances(ctx, req.(*DeleteInstancesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteInstancesResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_CreateVpc0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateVpcRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/CreateVpc")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateVpc(ctx, req.(*CreateVpcRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateVpcResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_DeleteVpc0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteVpcRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/DeleteVpc")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteVpc(ctx, req.(*DeleteVpcRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteVpcResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_ListVpcs0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListVpcsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/ListVpcs")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListVpcs(ctx, req.(*ListVpcsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListVpcsResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_ShowVpc0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ShowVpcRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/ShowVpc")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ShowVpc(ctx, req.(*ShowVpcRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ShowVpcResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_UpdateVpc0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateVpcRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/UpdateVpc")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateVpc(ctx, req.(*UpdateVpcRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateVpcResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_CreateSubnet0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSubnetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/CreateSubnet")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSubnet(ctx, req.(*CreateSubnetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSubnetResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_DeleteSubnet0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSubnetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/DeleteSubnet")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSubnet(ctx, req.(*DeleteSubnetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteSubnetResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_ListSubnets0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSubnetsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/ListSubnets")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSubnets(ctx, req.(*ListSubnetsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSubnetsResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_ShowSubnet0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ShowSubnetRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/ShowSubnet")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ShowSubnet(ctx, req.(*ShowSubnetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ShowSubnetResponse)
		return ctx.Result(200, reply)
	}
}

func _Instance_UpdateSubnet0_HTTP_Handler(srv InstanceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateSubnetRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, "/api.instance.v1.Instance/UpdateSubnet")
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateSubnet(ctx, req.(*UpdateSubnetRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateSubnetResponse)
		return ctx.Result(200, reply)
	}
}

type InstanceHTTPClient interface {
	CreateInstances(ctx context.Context, req *CreateInstancesRequest, opts ...http.CallOption) (rsp *CreateInstancesResponse, err error)
	CreateSubnet(ctx context.Context, req *CreateSubnetRequest, opts ...http.CallOption) (rsp *CreateSubnetResponse, err error)
	CreateVpc(ctx context.Context, req *CreateVpcRequest, opts ...http.CallOption) (rsp *CreateVpcResponse, err error)
	DeleteInstances(ctx context.Context, req *DeleteInstancesRequest, opts ...http.CallOption) (rsp *DeleteInstancesResponse, err error)
	DeleteSubnet(ctx context.Context, req *DeleteSubnetRequest, opts ...http.CallOption) (rsp *DeleteSubnetResponse, err error)
	DeleteVpc(ctx context.Context, req *DeleteVpcRequest, opts ...http.CallOption) (rsp *DeleteVpcResponse, err error)
	ListImages(ctx context.Context, req *ListImagesRequest, opts ...http.CallOption) (rsp *ListImagesResponse, err error)
	ListInstanceTypes(ctx context.Context, req *ListInstanceTypesRequest, opts ...http.CallOption) (rsp *ListInstanceTypesResponse, err error)
	ListInstances(ctx context.Context, req *ListInstancesRequest, opts ...http.CallOption) (rsp *ListInstancesResponse, err error)
	ListRegions(ctx context.Context, req *ListRegionsRequest, opts ...http.CallOption) (rsp *ListRegionsResponse, err error)
	ListSubnets(ctx context.Context, req *ListSubnetsRequest, opts ...http.CallOption) (rsp *ListSubnetsResponse, err error)
	ListVpcs(ctx context.Context, req *ListVpcsRequest, opts ...http.CallOption) (rsp *ListVpcsResponse, err error)
	RebootInstances(ctx context.Context, req *RebootInstancesRequest, opts ...http.CallOption) (rsp *RebootInstancesResponse, err error)
	ShowJob(ctx context.Context, req *ShowJobRequest, opts ...http.CallOption) (rsp *ShowJobResponse, err error)
	ShowSubnet(ctx context.Context, req *ShowSubnetRequest, opts ...http.CallOption) (rsp *ShowSubnetResponse, err error)
	ShowVpc(ctx context.Context, req *ShowVpcRequest, opts ...http.CallOption) (rsp *ShowVpcResponse, err error)
	StartInstances(ctx context.Context, req *StartInstancesRequest, opts ...http.CallOption) (rsp *StartInstancesResponse, err error)
	StopInstances(ctx context.Context, req *StopInstancesRequest, opts ...http.CallOption) (rsp *StopInstancesResponse, err error)
	UpdateSubnet(ctx context.Context, req *UpdateSubnetRequest, opts ...http.CallOption) (rsp *UpdateSubnetResponse, err error)
	UpdateVpc(ctx context.Context, req *UpdateVpcRequest, opts ...http.CallOption) (rsp *UpdateVpcResponse, err error)
}

type InstanceHTTPClientImpl struct {
	cc *http.Client
}

func NewInstanceHTTPClient(client *http.Client) InstanceHTTPClient {
	return &InstanceHTTPClientImpl{client}
}

func (c *InstanceHTTPClientImpl) CreateInstances(ctx context.Context, in *CreateInstancesRequest, opts ...http.CallOption) (*CreateInstancesResponse, error) {
	var out CreateInstancesResponse
	pattern := "/api/instances"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/CreateInstances"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) CreateSubnet(ctx context.Context, in *CreateSubnetRequest, opts ...http.CallOption) (*CreateSubnetResponse, error) {
	var out CreateSubnetResponse
	pattern := "/api/subnet"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/CreateSubnet"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) CreateVpc(ctx context.Context, in *CreateVpcRequest, opts ...http.CallOption) (*CreateVpcResponse, error) {
	var out CreateVpcResponse
	pattern := "/api/vpc"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/CreateVpc"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) DeleteInstances(ctx context.Context, in *DeleteInstancesRequest, opts ...http.CallOption) (*DeleteInstancesResponse, error) {
	var out DeleteInstancesResponse
	pattern := "/api/instances/terminate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/DeleteInstances"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) DeleteSubnet(ctx context.Context, in *DeleteSubnetRequest, opts ...http.CallOption) (*DeleteSubnetResponse, error) {
	var out DeleteSubnetResponse
	pattern := "/api/subnet"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/DeleteSubnet"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) DeleteVpc(ctx context.Context, in *DeleteVpcRequest, opts ...http.CallOption) (*DeleteVpcResponse, error) {
	var out DeleteVpcResponse
	pattern := "/api/vpc"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/DeleteVpc"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) ListImages(ctx context.Context, in *ListImagesRequest, opts ...http.CallOption) (*ListImagesResponse, error) {
	var out ListImagesResponse
	pattern := "/api/images"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/ListImages"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) ListInstanceTypes(ctx context.Context, in *ListInstanceTypesRequest, opts ...http.CallOption) (*ListInstanceTypesResponse, error) {
	var out ListInstanceTypesResponse
	pattern := "/api/instance-types"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/ListInstanceTypes"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...http.CallOption) (*ListInstancesResponse, error) {
	var out ListInstancesResponse
	pattern := "/api/instances"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/ListInstances"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) ListRegions(ctx context.Context, in *ListRegionsRequest, opts ...http.CallOption) (*ListRegionsResponse, error) {
	var out ListRegionsResponse
	pattern := "/api/regions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/ListRegions"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) ListSubnets(ctx context.Context, in *ListSubnetsRequest, opts ...http.CallOption) (*ListSubnetsResponse, error) {
	var out ListSubnetsResponse
	pattern := "/api/subnet"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/ListSubnets"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) ListVpcs(ctx context.Context, in *ListVpcsRequest, opts ...http.CallOption) (*ListVpcsResponse, error) {
	var out ListVpcsResponse
	pattern := "/api/vpc"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/ListVpcs"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) RebootInstances(ctx context.Context, in *RebootInstancesRequest, opts ...http.CallOption) (*RebootInstancesResponse, error) {
	var out RebootInstancesResponse
	pattern := "/api/instances/reboot"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/RebootInstances"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) ShowJob(ctx context.Context, in *ShowJobRequest, opts ...http.CallOption) (*ShowJobResponse, error) {
	var out ShowJobResponse
	pattern := "/api/job"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/ShowJob"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) ShowSubnet(ctx context.Context, in *ShowSubnetRequest, opts ...http.CallOption) (*ShowSubnetResponse, error) {
	var out ShowSubnetResponse
	pattern := "/api/subnet/query"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/ShowSubnet"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) ShowVpc(ctx context.Context, in *ShowVpcRequest, opts ...http.CallOption) (*ShowVpcResponse, error) {
	var out ShowVpcResponse
	pattern := "/api/vpc/query"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/ShowVpc"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) StartInstances(ctx context.Context, in *StartInstancesRequest, opts ...http.CallOption) (*StartInstancesResponse, error) {
	var out StartInstancesResponse
	pattern := "/api/instances/start"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/StartInstances"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) StopInstances(ctx context.Context, in *StopInstancesRequest, opts ...http.CallOption) (*StopInstancesResponse, error) {
	var out StopInstancesResponse
	pattern := "/api/instances/stop"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/StopInstances"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) UpdateSubnet(ctx context.Context, in *UpdateSubnetRequest, opts ...http.CallOption) (*UpdateSubnetResponse, error) {
	var out UpdateSubnetResponse
	pattern := "/api/subnet"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/UpdateSubnet"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *InstanceHTTPClientImpl) UpdateVpc(ctx context.Context, in *UpdateVpcRequest, opts ...http.CallOption) (*UpdateVpcResponse, error) {
	var out UpdateVpcResponse
	pattern := "/api/vpc"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation("/api.instance.v1.Instance/UpdateVpc"))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
